CREATE SCHEMA IF NOT EXISTS `student_portal`;

USE student_portal;

CREATE TABLE IF NOT EXISTS Students(
	StudentID INT NOT NULL UNIQUE AUTO_INCREMENT,
    Name VARCHAR(255) NOT NULL,
    Major VARCHAR(255) DEFAULT 'Undeclared',
    PRIMARY KEY (StudentID)
);
CREATE TABLE IF NOT EXISTS Courses(
    CourseID INT NOT NULL UNIQUE AUTO_INCREMENT,
	CourseName VARCHAR(255) NOT NULL,
    CourseMajor VARCHAR(255) NOT NULL,
    CourseUnits SMALLINT,
    CourseTitle VARCHAR(255),
    CourseDescription VARCHAR(500),
    PRIMARY KEY (CourseID)
);
CREATE TABLE IF NOT EXISTS Professors(
	ProfessorID INT NOT NULL UNIQUE AUTO_INCREMENT,
    Department VARCHAR(255),
    PRIMARY KEY (ProfessorID)
);
CREATE TABLE IF NOT EXISTS Sections(
	SectionID INT NOT NULL UNIQUE AUTO_INCREMENT,
    CourseID INT NOT NULL UNIQUE AUTO_INCREMENT,
    StudentID INT NOT NULL UNIQUE AUTO_INCREMENT,
    PRIMARY KEY (SectionID)
);
CREATE TABLE IF NOT EXISTS Enrollment(
	SectionID INT NOT NULL UNIQUE AUTO_INCREMENT,
	StudentID INT NOT NULL UNIQUE AUTO_INCREMENT,
	Term VARCHAR(255),
    PRIMARY KEY (StudentID)
);
CREATE TABLE IF NOT EXISTS Messages(
	MessageID INT NOT NULL UNIQUE AUTO_INCREMENT,
	StudentID INT NOT NULL UNIQUE AUTO_INCREMENT,
	MessageTITLE VARCHAR(255) NOT NULL,
    MessageDate DATETIME DEFAULT CURRENT_TIMESTAMP,
    MessageBody LONGTEXT,
    PRIMARY KEY (MessageID)
);
CREATE TABLE IF NOT EXISTS Grades(
	StudentID INT NOT NULL UNIQUE AUTO_INCREMENT,
    SectionID INT NOT NULL UNIQUE AUTO_INCREMENT,
    Grade CHAR(25) DEFAULT 'NC',
    Units SMALLINT NOT NULL,
    PRIMARY KEY (StudentID)
);